### PR TITLE
Fix gVisor CRI setup in vHive orchestrator

### LINKED ISSUE #696: gVisor CRI setup in vHive orchestrator skips orchestrator setup steps
Apparently, gVisor CRI setup is done wrong:
https://github.com/vhive-serverless/vHive/blob/2d014492e0c5ab5ec880b9204c746a2025089b63/vhive.go#L94-L99

It skips several orchestrator setup parts, e.g., the logger setup:
https://github.com/vhive-serverless/vHive/blob/2d014492e0c5ab5ec880b9204c746a2025089b63/vhive.go#L116-L129

AFAIC, it should be done in the same place as firecracker CRI setup:
https://github.com/vhive-serverless/vHive/blob/2d014492e0c5ab5ec880b9204c746a2025089b63/vhive.go#L149

### PR DESCRIPTION
**Pull request by CuriousGeorgiy**
## Summary

Closes #696

## Implementation Notes :hammer_and_pick:

* Setup gVisor CRI at the same place as firecracker CRI.

## External Dependencies :four_leaf_clover:

* N/A

## Breaking API Changes :warning:

* N/A

*Simply specify none (N/A) if not applicable.*

### CODE REVIEW

File: vhive.go [hunk 1]
```diff
@@ -265,28 +263,27 @@ func (s *fwdServer) FwdHello(ctx context.Context, in *hpb.FwdHelloReq) (*hpb.Fwd
...
-		return fmt.Errorf("failed to listen: %v", err)
+		log.Fatalf("failed to listen: %v", err)
 	}
 
 	s := grpc.NewServer()
 
 	gvService, err := gvcri.NewGVisorService()
 	if err != nil {
-		return fmt.Errorf("failed to create firecracker service %v", err)
+		log.Fatalf("failed to create firecracker service %v", err)
```
Comment (leokondrashov) [inline vhive.go:276]:
```suggestion
		log.Fatalf("failed to create gvisor service %v", err)
```

**Review by leokondrashov — COMMENTED** [review]
Apart from my suggestion, LGTM.
It fixes log collection, but in this logs there is a fatal error `Failed to start containerd clientfailed to dial \"/run/firecracker-containerd/containerd.sock\": context deadline exceeded`. I think that's the issue for separate PR.

**Comment by ustiugov** [comment]
LGTM.

File: vhive.go (hunk 1 above)
Comment (CuriousGeorgiy) [reply vhive.go]: Thanks for noticing, applied your suggestion!

Comment (CuriousGeorgiy) [reply vhive.go]: > It fixes log collection, but in this logs there is a fatal error `Failed to start containerd clientfailed to dial \"/run/firecracker-containerd/containerd.sock\": context deadline exceeded`. I think that's the issue for separate PR.

This happened, because AFAIU the orchestrator object (which starts `firecracker-containerd`) is only used by firecracker — adjusted the patch accordingly, now it works.

**Comment by CuriousGeorgiy** [comment]
@leokondrashov @ustiugov I tested that single node function deployment from the quickstart guide works for firecracker and gVisor setups.

**Review by ustiugov — APPROVED** [review]
